= Agent Evaluation with MLflow and EvalHub on Red Hat OpenShift AI
:navtitle: Home

== Goal

This course teaches how to deploy MLflow and EvalHub as included with Red Hat OpenShift AI 3.4; how to run evaluations of a self-hosted model, using EvalHub; how to run evaluations of an agentic application, using the MLflow SDK with Python; and how to visualize the results of those evaluations as MLflow experiments and traces using the Red Hat OpenShift AI dashboard.

Total estimated reading time: pass:[<span class="course-total-duration" aria-live="polite">…</span>]

You should reserve between 4 hours to one working day to complete this course.

This is the second in a series of quick courses covering MLflow, which consists of two courses:

. https://redhatquickcourses.github.io/rhoai-mlflow-traces/[Agent Traces with MLflow and Red Hat OpenShift AI^] (optional prerequisite course)

. *Agent Evaluation with MLFLow and EvalHub on Red Hat OpenShift AI* (this course)

IMPORTANT: Red Hat associates must enroll using the https://training-lms.redhat.com/sso/saml/auth/rhlpint?RelayState=deeplinkoffering%3D93435337[Red Hat Learning Portal^], and Red Hat Partners must enroll using https://training-lms.redhat.com/sso/saml/auth/rhopen?RelayState=deeplinkoffering%3D93435699[Red Hat Partner Connect^] to register this course in their learning history.

== Objectives

On completing this course, you should be able to:

* Understand how MLflow and EvalHub relate to agentic applications and to Red Hat OpenShift AI

* Deploy a development environment with MLflow and EvalHub

* Evaluate large language models (LLMs) using EvalHub

* Evaluate agents using MLflow

== Audience

* Software developers working on agentic applications and agentic harnesses.

* Red Hat and Partner roles that perform demonstrations, PoC, and PoV of MLflow with Red Hat OpenShift AI, such as Solutions Architects.

* Red Hat and Partner roles that implement and support MLflow and EvalHub with Red Hat OpenShift AI, such as Services Consultants, Technical Account Managers, and Customer Support Engineers.

== Prerequisites

This course assumes that you have the following experience:

* Familiarity with generative AI and agentic application concepts.

* Familiarity with the basic operation of Red Hat OpenShift AI.

* Python programming skills are recommended but not required, because this training provides sample code which is ready to run.

It is recommended, but not required, to attend a prerequisite course: https://redhatquickcourses.github.io/rhoai-mlflow-traces/[Agent Traces with MLflow and Red Hat OpenShift AI^].

== Classroom environment

This course uses the https://catalog.demo.redhat.com/catalog/babylon-catalog-prod?item=babylon-catalog-prod/published.openshift-ai-v3.prod&utm_source=webapp&utm_medium=share-link[Red Hat OpenShift AI 3.4^] demo catalog entry, which provides an SNO OpenShift cluster based on an AWS instance with a single GPU and a predeployed llama-32-3b-instruct model.

Any additional components required by MLflow, EvalHub, or course activities are configured by learners as part of course activities, using sample Python code and Kubernetes manifests provided in a public Git repository.

== Other sources of information about MLflow and EvalHub

For documentation about Red Hat OpenShift AI, see its https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed[product documentation^], especially:

* https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4/html/working_with_mlflow/index[Working with MLflow^]
* Chapter 2 of Evaluating AI systems: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4/html/evaluating_ai_systems/evaluating-llms-with-evalhub_evaluate[Evaluate LLMs with EvalHub^]

Also refer to upstream documentation of https://mlflow.org/docs/latest/index.html[MLflow^] and https://eval-hub.github.io/[EvalHub^].

== Author

*Fernando Lozano* +
Training Content Architect +
Red Hat - Product Portfolio Marketing & Learning

_Special thanks to Ahsen Shah, Edson Tirelli, and Matthew Prahl for their support while designing and writing this course._
