site:
  title: Agent Evaluation with MLFLow and EvalHub on Red Hat OpenShift AI
  start_page: rhoai-mlflow-evals::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  attributes:
    page-pagination: true
    experimental: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
