= Agentic Evaluation Concepts

Objective::

Describe the different kinds of assessment for agentic applications and explain how to code MLflow evaluations using scorers, judges, and data sets.

== MLflow assessments and evaluations

MLflow provides observability of gen AI applications in the form of _traces_, which record data about the conversation between an application and an LLM, such as:

* Inputs: system prompts, user prompts, tools lists, and other data in the context of an LLM.
* Outputs: responses returned by an LLM.
* Attributes: model name, context window size, and user-defined values.
* Metrics: time to first token, execution time in the LLM, and token cost.

Traces record multiple _spans_, which are internal conversations between an application and an LLM before it produces the final response, for example, when an LLM requests tool calls, and they can be grouped into _sessions_ for interactive conversations.

Traces and sessions are grouped in _experiments_, which, in turn, are grouped in _workspaces_.
A workspace in MLflow maps to an OpenShift project or Kubernetes namespace.

MLflow also enables recording the results of _assessments_ in a trace.
A _human assessment_ is based on judgment of the user, such as from thumbs up and down buttons.
AI-enabled applications can use the MLflow SDK or OpenTracing to store human assessments from its users.
Alternatively, an application can process stored traces and add such assessments after the fact.

Human assessments do not scale well, and MLflow offers automated assessments in the form of _scorer_ functions.
Using the MLflow SDK, you can create your custom scorer functions based on whatever criteria makes sense for your business.
They could search facts in a database, match regular expressions, or employ any other approach to verify the quality and correctness of a response.

But processing free-form text is incredibly hard.
And that is assuming your agent deals only with text.
MLflow also supports the concept of _LLM judges_ where you use an LLM to perform an assessment. 

The LLM that runs a judge is usually different from the LLM used by an application, though it could be the same one.
Some models perform better as judges than at tool calling, for example.
Or some tasks may perform well with a small model, but judging their responses requires a larger model.

MLflow provides a number of predefined LLM judges, which are basically prompts which are ready to use, but you can create your custom judges and define their prompts yourself.

An MLflow evaluation uses an _evaluation data set_, which provides not only inputs (prompts) for the application being evaluated, but also expected responses.
LLM judges usually perform their assessments by comparing the actual response with the expected response from the evaluation data set.

You can run an MLflow evaluation by creating custom code which refers to an AI-enabled application (an agentic application), an evaluation data set, and a list of scorers.

The upstream MLflow also supports other ways of running evaluations, such as defining jobs that perform post-processing of stored traces, but these capabilities are not yet supported as part of Red Hat OpenShift AI (RHOAI) because they depend on components of MLflow, such as its own AI gateway, which are not included with RHOAI.

Despite that limitation, nothing prevents you from emulating such capability by creating custom code ny using the MLflow SDK and running it from Jupyter notebooks, Kubeflow pipelines, or even OpenShift pipelines, among other alternatives.

== Coding MLflow evaluations

An MLflow evaluation is essentially a call to `mlflow.genai.evaluate` with three arguments:

`data`::
An evaluation data set.

`predict_fn`::
A predictor function, which encapsulates your entire AI-enabled application and its harness.

`scorers`::
A list of scorer functions.
The list can mix custom scorers and built-in scorers.

An evaluation data set can be defined inline by your code, stored in the MLflow server, or retrieved from external data sources by using libraries such as Pandas.

The `evaluate` function from MLflow expects that an evaluation data set is a list of objects which contains keys such as:

`inputs.question`::
The user prompt.

`expectations.expected_answer`::
A correct reference response to the user prompt.

Evaluation data sets could contain many other keys, some of which are specific to LLM judges, for example, to indicate you expect a helpful or formal tone, or to indicate that you expect that the response includes a plan or reasoning before delivering the final response.

Finally, a predictor function takes a single string argument, which is the user prompt, and returns a string result, which is the final response.
It is responsible for setting up your agentic harness, for example, its system prompt, tool lists, and RAG sources.

A predictor function is also expected to set up MLflow tracing, if the actual application does not.

The following snippet provides a minimal evaluation data set, containing a single item, and runs an evaluation based on a built-in LLM judge:

[source,python,subs="verbatim,quotes"]
--
eval_dataset = [
    {
        "inputs": {"question":
            "What's the difference between RHEL and CentOS?"},
        "expectations": {"expected_response":
            """
            RHEL and CentOS are both Linux distributions. RHEL is a proprietary distribution from Red Hat, while CentOS is community-supported. CentOS is a direct upstream of RHEL.
            """},
    },
]

results = mlflow.genai.evaluate(
    data=eval_dataset,
    predict_fn=my_predict_fn,
    scorers=[Correctness],
)
--

The previous snippet omits a predictor function, but you can view a complete example in the next activity.

== Creating deterministic scorers

Traditional code-based scorer functions, which do not use an LLM, are often called deterministic scorers.
They usually consider only the responses from LLMs, ignoring everything else from either the trace or evaluation data sets.

A scorer function is decorated with `@scorer` and could just return a boolean or numeric value, but it is recommended that scorer functions return a `Feedback` object that includes a reasoning for its assessment.
MLflow evaluations record that reasoning in traces to support human verification and troubleshooting.

== Creating LLM judges

MLflow provides a number of https://mlflow.org/docs/latest/genai/eval-monitor/scorers/llm-judge/predefined/#available-judges[built-in judges^], from generic ones such as `RelevanceToQuery` or `Correctness` to very specific ones that assess the usage of RAG sources and tool calls.
They also include judges specialized in multi-turn conversations, for example, `UserFrustration`.

Those built-in judges use the OpenAI API to invoke a model and by default require valid OpenAI keys for cloud-based models, but can be configured by setting standard OpenAI environment variables to invoke self-hosted models.

You create your own LLM judge by calling the `make_judge` function and passing, as arguments, the prompt, model URL, and authentication token for the model.
You do not require setting OpenAI environment variables to use self-hosted models with your custom judges.

== MLflow and other programming language runtimes

Creating an MLflow evaluation requires writing some code using the MLflow SDK, which is available for Python and TypeScript.
Does that mean developers using other programming languages are excluded from tapping into MLflow evaluations?
No.

Because the predictor function encapsulates your entire AI application and its harness, it could invoke your actual application directly, by using the operating system `exec` system call or by invoking a REST API endpoint.

Applications developed using accepted best practices usually provide an agentic backend, which is decoupled from its user interface, that can be invoked in one of those ways.
If your application does not, it is worth considering such a refactoring.
Improving testability of an application usually brings numerous maintenance benefits.

Alternatively, you can write code that retrieves traces of your application from MLflow and run evaluations on those traces.
This course does not provide an example of either approach, but the https://mlflow.org/docs/latest/genai/[upstream documentation^] of MLflow should provide sufficient information for implementing those approaches.

== What is next

Next, you evaluate a chat application by using a deterministic scorer and view the results as MLflow traces.

////
Evaluating agentic applications
Kinds of assessment: human, deterministic, and LLM judge.
MLflow evaluation scorers (deterministic) and prediction functions
MLflow built-in and custom LLM judges
Evaluation data sets: inline, in MLflow database, and extracted from traces
Coding an MLflow evaluation in Python
How to run MLflow evaluations with agents coded using runtimes other than Python and TypeScript
////