= Lab: Evaluate an Agent with Deterministic Scoring

Objective::

Starting from an agent that already produces MLflow traces, create a deterministic scorer and run an MLflow evaluation to verify response quality of that agent.

== Before you begin

You need access to the predeployed Red Hat OpenShift AI (RHOAI) instance provided in your lab environment. Ensure you have:

* Access credentials for the RHOAI dashboard
* A web browser to access the RHOAI dashboard
* Access credentials for the OpenShift web console

Also ensure that you already deployed MLflow and created a RHOAI workbench by following the instructions from xref:ch2-deployment:s2-mlflow-deploy-lab.adoc[chapter 2].

== Instructions

You will create and test MLflow scorer functions, using a Jupyter notebook. Then you will use the function for an MLflow evaluation of a simplistic agentic application that is provided to you.

As you perform this activity, you will alternate between two browser tabs:

* The Red Hat OpenShift AI (RHOAI) dashboard
* A Jupyter notebook from a RHOAI workbench

=== Review the sample agentic application

1. If you do not have a browser tab already open with the `test-mlflow` workbench, open it.

.. Open the RHOAI workbench and, in the left navigation pane, click menu:Projects[].
Select menu:All projects[] in the menu:Project[] field.
Then enter `my` in the *Filter by name* field and click menu:my-first-model[] in the list of projects.

.. In the *Projects* page for `my-first-model`, select the menu:Workbenches[] tab and click menu:test-mlflow[] to open its Jupyter Lab in a new browser tab.

2. Import the provided agentic application from git and test it.

.. In the toolbar of the left pane of the Jupyter notebook, click the menu:Git Clone[] icon and, in the *Clone a repo* pop-up, enter `\https://github.com/RedHatQuickCourses/rhoai-mlflow-samples.git`, which is the URL of the course samples repository.
Click menu:Clone[].
You should see, in the bottom right, the message `successfully cloned`.

.. In the left pane of the Jupyter notebook, enter the menu:rhoai-mlflow-samples/evals[] directory and double-click the menu:basic-agent.ipynb[] notebook to open it in a notebook tab.

.. Review the Python code for the agent.
It is a simplistic chat application that sets a hardcoded system prompt and submits a hardcoded question to a llama model, which is predeployed on your demo instance, using the OpenAI API.
+
The code in the notebook is split into multiple cells for readability, and it could be concatenated into a single Python script to run in a shell, but then it would require changes to use external URLs to access an inference service and MLflow, and to use authentication tokens.
+
NOTE: If you need more explanation about how that simplistic agent and its calls to MLflow tracing, please refer to the quick course about https://redhatquickcourses.github.io/rhoai-mlflow-traces/rhoai-mlflow-traces/1/ch3-collect-traces/s2-agent-traces-lab.html[MLflow traces^].

.. The notebook is ready to run as it is.
In the top toolbar of the notebook tab, click the menu:fast-forward[] icon with tooltip "Restart the kernel and run all cells".
In the *Restart Kernel* pop-up, click menu:Restart[].

.. Be patient while the first cell downloads Python packages from the RHOAI index, and the second cell submits to the Llama model a prompt asking: "What is RHEL?"
+
NOTE: You can ignore any warnings about `IProgress` and `ipywidgets`.

.. If all goes well, you should get a reasonable and correct response, though a rather long one.
Following is an example from testing these instructions:
+
[source,,subs="verbatim"]
--
**Red Hat Enterprise Linux (RHEL)**

* Developed and maintained by Red Hat, Inc.
* Licensed under the Red Hat Enterprise Linux License, which requires a subscription and support fees
* Supports a wide range of hardware and software platforms
* Includes commercial support, updates, and security patches for a fee
* Typically used in production environments, data centers, and enterprise settings

**CentOS**

* Originally based on RHEL 5, but now uses RHEL 8 as its base
* Developed by a community of volunteers, led by Red Hat
* Licensed under the GNU General Public License (GPL), which is free and open-source
* No subscription or support fees required
* Often used in development, testing, and education environments, as well as in some production environments where cost is a concern

In summary, RHEL is a commercial Linux distribution that requires a subscription and support fees, while CentOS is a free and open-source distribution that is based on RHEL but is not directly supported by Red Hat.
--

3. Visualize the MLflow trace generated by the agent.

.. Switch to the RHOAI dashboard and, in the left navigation pane, select menu:Develop & train[Experiments (MLflow)].
If the current project is not already `my-first-model`, enter `my` in the menu:Project[] field and click menu:my-first-model[].

.. The *Experiments* page should display both the `garak-evalhub` experiment from the previous chapter and the `simple-agent` experiment from this activity.
Click menu:simple-agent[] to open its experiment details page and click menu:Traces[].

.. You should see a single row, which displays the request and response from the agent, and metrics such as token count and execution time, but no assessments.
The `OK` state just means the agent performed the request and produced a response without execution errors.

.. Click either the trace id or the request on the single row to open a trace summary pane.
Then click menu:Show assessments[] to open its assessments pane.
It is empty, displaying only buttons to add feedback and expectations.

.. Return to the traces table by clicking the close button of the trace summary pane, which is the menu:x[] icon at its top right corner.
Do _not_ click the similar icon inside the assessments pane!

=== Evaluate the agent using a deterministic scorer function

[start=4]
4. Create and test a deterministic scorer function to assess the length of a response.
+
NOTE: You can see the complete code, ready to run evaluations, in the `deterministic-eval-complete.ipynb` notebook, in the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/blob/main/evals/deterministic-eval-complete.ipynb[course samples repository^].

.. Copy the basic-agent notebook to a new file that you will edit.
+
Switch to your JupyterLab and, in its left pane, right-click menu:basic-agent.ipynb[] and select menu:Duplicate[].
Then right-click the new file menu:basic-agent-Copy1.ipynb[] and select menu:Rename[].
Enter `deterministic-eval.ipynb` as the new file name.
Finally, double-click menu:deterministic-eval.ipynb[] to open the notebook in a new editor tab.

.. In the cell, enter the code for a scorer function which checks the length of a response based on the number of words.
+
In the `deterministic-eval.ipynb` notebook, select the last cell, having the comment `###Cell 6: run the agent`.
Then click, in the cell's toolbar, the icon to menu:Insert a cell bellow[].
Inside the new cell, enter the following code.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 7: deterministic scorer

from mlflow.genai.scorers import scorer
from mlflow.entities import Feedback

@scorer
def one_to_three_short_sentences(outputs: str) -> Feedback:
    """15-20 words per sentence, up to three sentences"""
    word_count = len(outputs.split())
    metric={
        "word-count": word_count,
        "min": 20,
        "max": 60
    }
    pass_fail = word_count >=20 and word_count <=60
    if word_count < metric["min"]:
        return Feedback(
                name="short_response",
                value=False,
                rationale=f"Total word count was lower than {metric["min"]}: {word_count}.",
                metadata=metric
            )
    elif word_count > metric["max"]:
        return Feedback(
                name="short_response",
                value=False,
                rationale=f"Total word count was higher than {metric["max"]}: {word_count}.",
                metadata=metric
            )
    else:
        return Feedback(
                name="short_response",
                value=True,
                rationale=f"Total word count was between {metric["min"]} and {metric["max"]}: {word_count}.",
                metadata=metric
            )
--

.. In the cell's toolbar, click the menu:play[] icon with tooltip "Run this cell and advance" to define the function and create a new notebook cell.
Running the cell produces no output.

.. Inside the new cell, enter the code to test the scorer function from hardcoded examples.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 8: test scorer

feedback = one_to_three_short_sentences(
    outputs="RHEL (Red Hat Enterprise Linux) is a Linux distribution."
)
print(f"Test scorer with a too short response: {feedback.value} - {feedback.rationale}")

feedback = one_to_three_short_sentences(
    outputs="RHEL (Red Hat Enterprise Linux) is a commercial Linux distribution, supported by Red Hat and produced from CentOS Stream and Fedora Linux."
)
print(f"Test scorer with an OK long response: {feedback.value} - {feedback.rationale}")

feedback = one_to_three_short_sentences(
    outputs="""
        Red Hat Enterprise Linux (RHEL) is a commercial, stable, and secure version of Linux, supported by Red Hat and produced from from multiple upstreams.
        The direct upstream to RHEL is the CentOS Stream Linux distribution, which is a free, commumity-supported distribution.
        The Fedora Linux is a direct upstream to CentOS, and thus an indirect upstream to RHEL.
        RHEL is suitable for production environments, whereas Fedora is more experimental and intended for developers and power users.
        Fedora is often used as a testing ground for new features and technologies before they are included in RHEL.
        Fedora Linux is free and commumity-supported.
    """
)
print(f"Test scorer with a too long response: {feedback.value} - {feedback.rationale}")
--

.. In the cell's toolbar, click the menu:play[] icon with tooltip "Run this cell and advance" to run the test code.
Running the cell produces the following output.
+
[source,,subs="verbatim,quotes"]
--
Test scorer with a too short response: False - Total word count was lower than 20: 9.
Test scorer with an OK long response: True - Total word count was between 20 and 60: 22.
Test scorer with a too long response: False - Total word count was higher than 60: 100.
--

5. Create code for running an MLflow evaluation using the deterministic scorer.

.. In the new, empty cell, created by running the test code for the scorer function, enter the code to define an evaluation data set.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 9: hardcoded evaluation data set

eval_dataset = [
    {
        "inputs": {"question":
            "What's the difference between RHEL and CentOS?"},
        "expectations": {"expected_response":
            """
            RHEL and CentOS are both Linux distributions. RHEL is a proprietary distribution from Red Hat, while CentOS is community-supported. CentOS is a direct upstream of RHEL.
            """},
    },
    {
        "inputs": {"question":
            "What's the difference between RHEL and Fedora Linux?"},
        "expectations": {"expected_response":
            """
            RHEL and Fedora are both Linux distributions. RHEL is a proprietary distribution from Red Hat, while Fedora is community-supported. Fedora is an upstream of RHEL.
            """},
    },
]
--

.. In the cell's toolbar, click the menu:play[] icon with tooltip "Run this cell and advance" to define the array and create a new notebook cell.
Running the cell produces no output.

.. Inside the new cell, enter the code to wrap the agent inside a predictor function and run an MLflow evaluation using your scorer function.
+
NOTE: The `MLFLOW_GENAI_EVAL_SKIP_TRACE_VALIDATION` environment variable prevents MLflow from performing a canary test using the first row of the evaluation data, which would produce duplicate traces and assessments for it.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 10: run evaluation

def my_predict_fn(question: str) -> str:
    return agent("no token", system_instructions, input_text)

os.environ["MLFLOW_GENAI_EVAL_SKIP_TRACE_VALIDATION"]="true"

try:
    results = mlflow.genai.evaluate(
        data=eval_dataset,
        predict_fn=my_predict_fn,
        scorers=[one_to_three_short_sentences],
    )
except Exception as e:
    print(f"An error occurred: {e}")
--

.. In the cell's toolbar, click the menu:play[] icon with tooltip "Run this cell and advance" to run the evaluation.
Monitor the evaluation progress meter and wait until it reaches 100%, meaning it ran all scorers over the complete evaluation data set.
When done, you should see an output similar to the following.
+
[source,,subs="verbatim,quotes"]
--
Evaluating: 100%|██████████| 2/2 [Elapsed: 00:01, Remaining: 00:00] [predict_fn: 98%, scorers: 2%]
--

6. View evaluation results on MLflow traces

.. Switch to your RHOAI dashboard, which should already be in the details page for the `simple-agent` experiment.
If it is not, select menu:Develop & train[Experiments (MLflow)], in the left navigation pane, and, in the menu:Project[] field, enter `my` and select menu:my-first-model[] and click menu:simple-agent[].

.. In the `simple-agent` experiment details page, click menu:Traces[] and notice, besides the two new traces, the new columns `short_response`, which display results from the scorer function.
If you do not see these changes, click the menu:Refresh[] icon next to the menu:Time range[] field.
+
Also notice that the trace for the previous run of the agent, which did no evaluation, displays `null` for that column.
+
Finally, notice that the top of the table displays a summary of the `short_response` score for all traces, with a 100% for the `False` value.

.. Click the trace ID, or the request of the most recent trace, which is the first row of the traces table, to view its trace summary panel.
It should display an *Assessment* pane, with the value of the `short_response` scorer.
Click the menu:>[] icon to expand the feedback results and view the rationale for the result.

.. Return to the traces table by clicking the close button of the trace summary pane, which is the menu:x[] icon at its top right corner.
Do _not_ click the similar icon in the assessments pane!

=== Improve the agent with a new system prompt from the MLflow prompt registry

[start=7]
7. Record a new system prompt in MLflow.
+
You already saw that the Llama model produces very long responses, by default.
It is standard practice to tweak the system prompt to control the tone and format of outputs from the agent.
But, instead of hardcoding a new system prompt in the agent, retrieve the prompt from MLflow.

.. Still in the `simple-agent` experiment details page, click menu:Prompts[]. 
Then click menu:Create prompt[].

.. In the *Create prompt* pop-up, enter `short-responses` in the *Name* field, and enter the following in the *Prompt* field:
+
[source,,subs="verbatim,quotes"]
--
You are a helpful assistant which provides short and objective responses, composed of one to three short sentences.
--

.. Click menu:Create[] to save the prompt.
Notice that it is saved as `version 1`.

8. Change the agent to use the new system prompt.
+
NOTE: You can see the complete code, ready to use the new system prompt, in the `deterministic-eval-new-prompt.ipynb` notebook, in the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/blob/main/evals/deterministic-eval-new-prompt.ipynb[course samples repository^].

.. Switch to your JupyterLab and its editor tab with the `deterministic-eval.ipynb` notebook and scroll up to its sixth cell, that starts with `###Cell 6: run the agent`.

.. Make the following changes to the code inside the cell to load and format the prompt from MLflow and use it as the system prompt.
Even though our new prompt contains no placeholders, it must still be formatted before passing to an LLM.
+
[source,python,subs="verbatim,quotes"]
--
...
try:
    *system_prompt = mlflow.genai.load_prompt("prompts:/short-responses/1")*
    *final_prompt = system_prompt.format()*
    response = agent("no token", *final_prompt*, input_text)    
    print(response)
except Exception as e:
    print(f"An error occurred: {e}")
--

.. In the cell's toolbar, click the menu:play[] icon with tooltip "Run this cell and advance" to run the agent using the new system prompt.
Its output should be very different from its previous run, and similar to the following.
+
[source,,subs="verbatim,quotes"]
--
RHEL (Red Hat Enterprise Linux) and CentOS are both Linux distributions, but they differ in their licensing and support. RHEL is a commercial distribution, while CentOS is an open-source distribution based on RHEL.
--

9. Run evaluations using the new system prompt

.. Scroll down to the tenth cell of the notebook, that starts with `###Cell 10: run evaluation`, and change its code to use the new system prompt.
+
[source,python,subs="verbatim,quotes"]
--
...
def my_predict_fn(question: str) -> str:
    *system_prompt = mlflow.genai.load_prompt("prompts:/short-responses/1")*
    *final_prompt = system_prompt.format()*
    return agent("no token", *final_prompt*, input_text)
...
--

.. In the cell's toolbar, click the menu:play[] icon with tooltip "Run this cell and advance" to run the agent using the new system prompt.
The output is the same as the previous attempt, because the code for evaluations does not print anything about the results, but just a progress meter.

.. Switch to the RHOAI dashboard, which should still be in the menu:Prompts[] tab of the experiment details page for `simple-agent`.
Select menu:Traces[] to open its list of traces.

.. You should see the new traces, from running the agent and the evaluation a second time.
If you do not, click the menu:Refresh[] icon near the menu:Time range[] field.
+
The new traces should display the values `null` and `True` in the `short_response` column, proving that the new system prompt had the desired effect.
The summary at the top of the table should now split 50%/50% between `True` and `False`.

=== Summary

You created a scorer function to assess the length of responses produced by the model, then you ran an evaluation wthathich showed the responses were too long.
Then you crafted a new system prompt, which you stored in the MLflow prompt registry, to direct the model to produce shorter responses.
After testing the agent using the new system prompt, you ran the same evaluation again, proving that now responses are short, as desired.

== What is next

Next, you evaluate the same application using built-in and custom LLM judges for more nuanced assessment.

////
Evaluate an agent with a deterministic function
Start from a ready-to-run chat application and validate it's fine
Add tracing to the chat app
CANNOT USE the RHOAI 3.4 index for MLflow and evals – there's a bug with using self-hosted models. Show how to switch to upstream package indexes.
Encapsulate the function in a prediction function and evaluate using a deterministic scorer for "short responses"
Provide evaluation data inline as Python code
Run the evaluation and view its results on MLflow traces
Show how changes to the system prompt change scores from fail to pass
Tentative: use MLflow prompt registry to fetch different system prompts for different experiments
////