= Lab: Evaluate an Agent with an LLM Judge

Objective::

Perform evaluations using built-in and custom LLM judges with self-hosted models, and inspect evaluation results through MLflow traces.

== Before you begin

You need access to the predeployed Red Hat OpenShift AI (RHOAI) instance provided in your lab environment. Ensure you have:

* Access credentials for the RHOAI dashboard
* A web browser to access the RHOAI dashboard
* Access credentials for the OpenShift web console

Also ensure that you already deployed MLflow and created a RHOAI workbench by following the instructions from xref:ch2-deployment:s2-mlflow-deploy-lab.adoc[chapter 2], and that you already cloned the sample notebooks from the course samples repository, by following the instructions from the xref:s2-deterministic-lab.adoc[previous lab].

== Instructions

You will create and test two LLM judges, one provided by MLflow and another using your custom prompt.
You will use them together for an MLflow evaluation of a simplistic agentic application that is provided to you.

As you perform this activity, you will alternate between two browser tabs:

* The Red Hat OpenShift AI (RHOAI) dashboard
* The Jupyter Lab from a RHOAI workbench

=== Create and test an LLM judge using one of the judges provided by MLflow

1. If you do not have a browser tab already open with the `test-mlflow` workbench, open it and, in its Jupyter Lab, enter the `rhoai-mlflow-samples/evals` directory.

.. Open the RHOAI workbench and, in the left navigation pane, click menu:Projects[].
Select menu:All projects[] in the menu:Project[] field.
Then enter `my` in the *Filter by name* field and click menu:my-first-model[] in the list of projects.

.. On the *Projects* page for `my-first-model`, select the menu:Workbenches[] tab and click menu:test-mlflow[] to open its Jupyter Lab in a new browser tab.

.. Copy the `simple-agent` notebook to a new file that you will edit.
In the left pane of JupyterLab, enter the menu:rhoai-mlflow-samples/evals[] directory, right-click menu:simple-agent.ipynb[], and select menu:Duplicate[].
Then right-click the new file menu:simple-agent-Copy1.ipynb[] and select menu:Rename[].
Enter `llm-eval.ipynb` as the new file name.
Finally, double-click menu:llm-eval.ipynb[] to open the notebook in a new editor tab.

.. In the toolbar of the notebook, click the menu:fast forward[] icon, with tooltip "Restart the kernel and run all cells".
In the *Restart kernel* pop-up, click menu:Restart[].
The output of the last cell should provide a short explanation about the differences between RHEL and CentOS.
+
NOTE: The code uses the prompt added to the MLflow prompt registry during the xref:s2-deterministic-lab.adoc[previous lab].

2. Create and test an LLM judge to assess the correctness of a response.
+
You can see the complete code, ready to use the built-in LLM judge, in the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/blob/main/evals/llm-eval-builtin.ipynb[llm-eval-builtin.ipynb^] notebook, in the course samples repository. 

.. Enter the model configurations for MLflow LLM judges.
+
In the `llm-eval.ipynb` notebook, select the third cell, with the comment `###Cell 3: environment settings` and append configuration and environment variables to configure MLflow to use the llama model available in your demo environment to run LLM judges.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 3: environment settings

import os

BASE_URL = "http://llama-32-3b-instruct-predictor.my-first-model.svc.cluster.local:8080/v1"
model_name = "llama-32-3b-instruct"

MLFLOW_TRACKING_URL = "https://mlflow.redhat-ods-applications.svc.cluster.local:8443"
MLFLOW_EXPERIMENT = "simple-agent"

os.environ["MLFLOW_TRACKING_AUTH"]="kubernetes-namespaced"

# New code starts here
*JUDGE_URL = BASE_URL
judge_model = model_name
os.environ["OPENAI_API_BASE"] = JUDGE_URL
os.environ["OPENAI_API_KEY"] = "no token"*
--

.. In the cell's toolbar, click the menu:play[] icon, with tooltip "Run this cell and advance" to define the new variables.
Running the cell produces no output.

.. Enter the code to instantiate a `Correctness` judge from MLflow.
+
In the `llm-eval.ipynb` notebook, select the last cell, having the comment `###Cell 6: run the agent`.
Then click, in the cell's toolbar, the icon to menu:Insert a cell below[].
Inside the new cell, enter the following code.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 7: LLM judges

from mlflow.genai.scorers import Correctness
from mlflow.genai.judges import make_judge

correctness_judge = Correctness(
    model=f"openai:/{judge_model}"
)
--

.. In the cell's toolbar, click the menu:play[] icon, with tooltip "Run this cell and advance" to define the function and create a new notebook cell.
Running the cell produces no output.

.. Inside the new cell, enter the code to test the LLM judge from hardcoded examples.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 8: test judges

print ("Test built-in judge:\n")
feedback = correctness_judge(
    inputs={"question": "What is RHEL?"},
    outputs={"response": "RHEL is a Linux distribution from Red Hat."},
    expectations={"expected_response": "RHEL (Red Hat Enterprise Linux) is a Linux distribution."},
)
print(f"• Test judge with correct definition of RHEL: {feedback.value}\n  {feedback.rationale}")

feedback = correctness_judge(
    inputs={"question": "What is RHEL?"},
    outputs={"response": "RHEL (Rebooting Helps Every Lag) is pun on IT struggles."},
    expectations={"expected_response": "RHEL (Red Hat Enterprise Linux) is a Linux distribution."},
)
--

.. In the cell's toolbar, click the menu:play[] icon, with tooltip "Run this cell and advance" to run the test code.
Running the cell produces an output similar to the following.
+
[source,,subs="verbatim,quotes"]
--
Test built-in judge:

• Test judge with correct definition of RHEL: yes
  The first statement in the claim is 'RHEL' which is supported by the document as the question and response both mention 'RHEL'. The second statement in the claim is 'is a Linux distribution' which is also supported by the document as the response explicitly states 'a Linux distribution from Red Hat'.
• Test judge with incorrect definition of RHEL: no
  The claim states RHEL is a Linux distribution. The document does not mention Linux distribution, it mentions a pun on IT struggles.
--

=== Create and test an LLM judge using a custom prompt

[start=3]
3. Create and test an LLM judge to assess that a response contains no acronyms.
+
You can see the complete code, ready to use the built-in LLM judge, in the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/blob/main/evals/llm-eval-custom.ipynb[llm-eval-custom.ipynb^] notebook, in the course samples repository. 

.. Select the first cell that you just added to the notebook, the one starting with `###Cell 7: LLM judges`, and append code to create a custom judge.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 7: LLM judges

from mlflow.genai.scorers import Correctness

correctness_judge = Correctness(
    model=f"openai:/{judge_model}"
)

# New code starts here
from mlflow.genai.judges import make_judge

*acronyms_judge = make_judge(
    name="expanded_acronyms",
    instructions=(
        "Check if this text expands any common IT acronyms or product names:\n"
        "{{ outputs }}"
        "\n\nEVALUATION STEPS:\n"
        "1. Scan the text for IT acronyms (e.g., TCP, IP, AI, LLM) or similar names (e.g., Vim, GNOME, LAME, RHEL).\n"
        "2. Check if the text explicitly expands them to their full words (e.g., 'LLM (Large-Language Model)', 'GNOME (GNU Network Object Model Environment).\n"
        "3. Merely explaining or describing a concept (e.g., 'Vim is a text editor') (e.g. 'RHEL is an operating system') does NOT count as an expansion.\n\n"
        "BOOLEAN OUTPUT:\n"
        "- Return True if you found ONE OR MORE acronym expansions.\n"
        "- Return False if the response is completely FREE of acronym expansions (NO expansions found).\n"
    ),
    feedback_value_type=bool,
    model=f"openai:/{judge_model}",
    inference_params={"temperature": 0.0},
    base_url=f"{JUDGE_URL}/chat/completions"*
)
--

.. In the cell's toolbar, click the menu:play[] icon, with tooltip "Run this cell and advance" to define the function and create a new notebook cell.
Running the cell produces no output.

.. Select the second cell that you just added to the notebook, the one starting with `###Cell 8: test judges`, and append code to test the custom judge.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 8: test judges

print ("Test built-in judge:\n")
...

# New code starts here
*print ("\nTest LLM judge:\n")

feedback = acronyms_judge(
    inputs={"question": "What is RHEL?"},
    outputs={"response": "RHEL is a Linux distribution."},
)
print(f"• Test judge with RHEL (no expansion): {feedback.value}\n  {feedback.rationale}")

feedback = acronyms_judge(
    inputs={"question": "Who supports RHEL?"},
    outputs={"response": "Red Hat provides commercial support for users of Linux."},
)
print(f"• Test judge with RHEL (no expansion): {feedback.value}\n  {feedback.rationale}")

feedback = acronyms_judge(
    inputs={"question": "What is RHEL?"},
    outputs={"response": "RHEL (Red Hat Enterprise Linux) is a Linux distribution."},
)
print(f"• Test judge with RHEL (expanded)': {feedback.value}\n  {feedback.rationale}")*
--

.. In the cell's toolbar, click the menu:play[] icon, with tooltip "Run this cell and advance" to run the test code.
Running the cell produces an output similar to the following.
+
[source,,subs="verbatim,quotes"]
--
Test built-in judge:
...

Test LLM judge:

• Test judge with RHEL (no expansion): False
  The text does not explicitly expand any IT acronyms or product names. Although it mentions 'RHEL', it only provides a brief description without expanding the acronym to its full word 'Linux distribution'. The text does not meet the criteria for an acronym expansion.
• Test judge with RHEL (no expansion): False
  The text does not explicitly expand any IT acronyms or product names. It only mentions 'Linux', which is a common operating system, but does not provide any expansion or explanation of the acronym.
• Test judge with RHEL (expanded)': True
  The text explicitly expands the acronym 'RHEL' to its full word 'Red Hat Enterprise Linux', indicating that it meets the criteria for evaluating the performance of an AI agent on this query.
--

=== Run an MLflow evaluation using both LLM judges

[start=4]
4. Create code for running an MLflow evaluation using the two LLM judges you tested in the previous steps.

.. In the new, empty cell, created by running the test code for the custom judge function, enter the code to define an evaluation data set.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 9: hardcoded evaluation data set

eval_dataset = [
    {
        "inputs": {"question":
            "What's the difference between RHEL and CentOS?"},
        "expectations": {"expected_response":
            """
            RHEL and CentOS are both Linux distributions.
            RHEL is a commercial distribution from Red Hat, while CentOS is a free distribution.
            CentOS Stream is a direct upstream of RHEL.
            """},
    },
    {
        "inputs": {"question":
            "What's the difference between RHEL and Fedora Linux?"},
        "expectations": {"expected_response":
            """
            RHEL and Fedora are both Linux distributions.
            RHEL is a commercial distribution from Red Hat, while Fedora is a free distribution.
            Fedora is an upstream of RHEL.
            """},
    },
]
--

.. In the cell's toolbar, click the menu:play[] icon, with tooltip "Run this cell and advance" to define the array and create a new notebook cell.
Running the cell produces no output.

.. Inside the new cell, enter the code to wrap the agent inside a predictor function and run an MLflow evaluation using your scorer function.
If you need, follow the instructions there to store the prompt.
+
[source,python,subs="verbatim,quotes"]
--
###Cell 10: run evaluation

def my_predict_fn(question: str) -> str:
    system_prompt = mlflow.genai.load_prompt("prompts:/short-responses/1")
    final_prompt = system_prompt.format()
    return agent("no token", final_prompt, input_text)

os.environ["MLFLOW_GENAI_EVAL_SKIP_TRACE_VALIDATION"]="true"

try:
    results = mlflow.genai.evaluate(
        data=eval_dataset,
        predict_fn=my_predict_fn,
        scorers=[correctness_judge,acronyms_judge],
    )
except Exception as e:
    print(f"An error occurred: {e}")
--

.. In the cell's toolbar, click the menu:play[] icon, with tooltip "Run this cell and advance" to run the evaluation.
Monitor the evaluation progress meter, and wait until it reaches 100%, meaning it ran all scorers over the complete evaluation data set.
When it is done, you should see an output similar to the following.
+
[source,,subs="verbatim"]
--
2026/08/03 16:47:51 INFO mlflow.models.evaluation.utils.trace: Auto tracing is temporarily enabled during the model evaluation for computing some metrics and debugging. To disable tracing, call `mlflow.autolog(disable=True)`.
Evaluating: 100%|██████████| 2/2 [Elapsed: 00:08, Remaining: 00:00] [predict_fn: 22%, scorers: 78%]
--

5. View evaluation results on MLflow traces.

.. Switch to your RHOAI dashboard, which should already be in the details page for the `simple-agent` experiment. If it is not, select menu:Develop & train[Experiments (MLflow)], in the left navigation pane, and, in the menu:Project[] field, enter `my` and select menu:my-first-model[] and click menu:simple-agent[].

.. In the `simple-agent` experiment details page, click menu:Traces[] and notice, besides a few new traces, the new columns `Correctness` and `expanded_acronyms`.
If you do not see these changes, click the menu:Refresh[] icon next to the menu:Time range[] field.

.. Consider just the two most recent traces, which contain the results of the last MLflow evaluation run on a sample of two prompts, and mouse over the values on their `Correctness` column to view the reasoning for the `Fail` and `Pass` grades of each trace.

.. On the same traces, mouse over the values of their `expanded_acronyms` column to view the reasoning between their `True` or `False` scores.

.. With any of the traces, if you cannot read the full reasoning by using mouse over, click on the trace id or its request and, if the *Assessments* page is not shown, click menu:Show assessments[]. 
Then you can expand each assessment to fully visualize its reasoning, and you can scroll down and up as you need.

.. You may note that the `expanded_acronyms` custom judge is not very reliable, which might be because of the quality of the prompt or by limitations of the llama model.
It is frequent to use different models or even larger models for judges than the models that might be good enough for an application.

.. You may get assessments and reasonings which seem odd or incorrect.
It is the nature of LLMs to sometimes hallucinate.
Feel free to run the evaluation multiple times, compare the responses of each attempt, and how the LLM judges assess each one.

=== Summary

You created two LLM judges, one to verify if a response is correct, by comparing with a correct response provided in the evaluation data set, and another to verify if a response expands acronyms, which would make it longer than necessary.
After testing each judge, you combined both in a single evaluation again, demonstrating that you can use multiple judges on the same evaluation data and visualize the results of multiple judges in the same MLflow trace.

== What is next

Congratulations on completing this course! You are now able to deploy MLflow and EvalHub on Red Hat OpenShift AI, evaluate both models and agentic applications, and visualize results using the RHOAI dashboard.

////
Evaluate an agent with an LLM judge
Start from the same application as the previous example
Perform an evaluation using a built-in LLM judge (Correctness), but using self-hosted models instead of external frontier models
View evaluation results on MLflow traces
Create a custom LLM judge (no acronyms?) using make_judge and test it with a direct call
Perform an evaluation using the custom LLM judge
View evaluation results on MLflow traces
Enable traces of evaluations
Tentative: use a MCP-enabled agentic app and a tool judge from MLflow
////