= Lab: Deploy MLflow for Development

Objective::

Deploy and verify a development instance of MLflow in Red Hat OpenShift AI.

WARNING: Pending Review

== Before you begin

You need access to the predeployed Red Hat OpenShift AI (RHOAI) instance provided in your lab environment. Ensure you have:

* Access credentials for the RHOAI dashboard
* A web browser to access the RHOAI dashboard
* Access credentials for the OpenShift web console

[NOTE]
====
If you are in a hurry and need to quickly enable MLflow in your demo instance, for example: you had to destroy and recreate it before completing all activities in this course, you can:

* Clone the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples.git[samples git repository^]
* Enter its `scripts` directory
* Log in to OpenShift in your demo instance as the `admin` user, using the `oc` command
* Invoke the `enable-mlflow.sh` script
====

== Instructions

You will enable MLflow on your Data Science Cluster singleton resource and deploy a development instance of the MLflow server.
Then you will create a Jupyter notebook to test connectivity to the MLflow server.
You will use the MLflow SDK for Python.

As you perform this activity, you will alternate between three browser tabs:

* The Red Hat OpenShift web console
* The Red Hat OpenShift AI (RHOAI) dashboard
* A Jupyter notebook from a RHOAI workbench

Once you open one of these tabs, keep it open because you may return to it later.

=== Install and configure the MLflow server

1. Enable MLflow on RHOAI by editing its data science cluster resource.

.. Open the OpenShift web console and log in as a user with `cluster-admin` rights.

.. In the left navigation pane, select menu:Ecosystem[Installed Operators].
Then click menu:Red Hat OpenShift AI[].

.. In the Red Hat OpenShift AI operator page, select the menu:Data Science Cluster[] tab.
Then click the menu:default-dsc[] resource.

.. In the `default-dsc` resource page, select the menu:YAML[] tab.
In the text editor, search for the `spec.components` field, and set `mlflowoperator.managementState` to `Managed`.
+
[source,yaml,subs="verbatim,quotes"]
----
...
spec:
  components:
    *mlflowoperator:*
      *managementState: Managed*
    kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headless
...
----

.. Click menu:Save[] and wait until you see a confirmation message similar to:
+
[source,none,subs="verbatim,quotes"]
----
alert:default-dsc has been updated to version 1186240
----

.. If you receive an error message, fix the errors in your YAML and try saving again.

2. Configure your MLflow instance by creating an MLflow resource.

.. Open the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/blob/main/scripts/mlflow.yaml[sample MLflow manifest^] from the course samples repository.
Copy the entire contents of the `scripts/mlflow.yaml` manifest to the clipboard.
+
NOTE: That manifest corresponds to the example from https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4/html/working_with_mlflow/installing-mlflow_mlflow#mlflow-configuration-parameters_mlflow[Minimal development or test deployment^] in the Red Hat OpenShift AI product documentation with no changes.
+
The full manifest is listed here, just for your reference:
+
[source,YAML,subs="verbatim,quotes"]
----
include::1@samples:scripts:example$mlflow.yaml[]
----

.. In the left navigation pane, select menu:Home[API Explorer].
Then enter `MLflow` in the search field.
You will see three resource types; click menu:MLflow[].

.. In the MLflow Resource details page, select the menu:Instances[] tab and click menu:Create MLflow[].

.. In the YAML text editor, delete all of its sample contents and paste the manifest you already copied to the clipboard.

.. Click menu:Create[] and, in the MLflow details page, wait until the `Available` condition is `True` and the `Progressing` condition is `False`.

=== Test your MLflow server using the dashboard and a workbench

[start=3]
3. Verify MLflow is available from RHOAI and create an empty experiment.

.. Open your RHOAI dashboard.
If it is already open, refresh your browser window.

.. In the left navigation pane, expand menu:Develop & train[].
Notice the new item named menu:Experiments (mlflow)[] and select it.

.. In the menu:Project[] field, select the menu:my-first-model[] project.

.. Click menu:Create Experiment[] and enter `dummy experiment` as its name.

.. Verify that you see the Experiments page for `dummy experiment` but there is no data on any of its pages, such as menu:Traces[], menu:Sessions[], or menu:Prompts[].

.. Creating an empty experiment is sufficient to prove that your MLflow instance can connect to its database and artifacts storage.

.. You can, alternatively, open the upstream MLflow web interface by clicking the menu:applications[] menu, near the top right of the navigation bar close to the help icon, and selecting menu:MLflow[].
You should not need it: all functionality you need for this course is available from the RHOAI dashboard.

4. Test connectivity to MLflow from a Jupyter notebook inside a workbench.
+
NOTE: If you have trouble typing the Python code in this and other activities of this course, or you cannot cut-and-paste from the course page, you can access the complete source code for all Jupyter notebooks in the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/tree/main/traces[course samples git repository^].

.. In the left navigation pane, select menu:All projects[] in the menu:Project[] field.
Then enter `my` in the *Filter by name* field and click menu:my-first-model[] in the list of projects.

.. In the Projects page for `my-first-model`, select the menu:Workbenches[] tab and click menu:Create workbench[].

.. In the Create workbench page, enter `test-evals` for the *Name* field and, in the *Workbench image* field, select menu:Jupyter | Minimal | CPU[].

.. Leave all other fields with their default values and click menu:Create workbench[].

.. In the Workbenches list, wait until the row for the `test-evals` workbench displays a `Ready` state and then click menu:test-evals[] to open its Jupyter Lab in a new browser tab.

.. Click the menu:Python 3.12[] Notebook icon to create an empty notebook.
In the left navigation pane of the Jupyter Lab, right-click the menu:Untitled.ipynb[] file, which is your new notebook, and select menu:Rename[].
Then, enter `test-mlflow.ipynb` as its new file name.

.. In the first cell of your notebook, enter:
+
[source,python,subs="verbatim,quotes"]
----
! pip install mlflow[kubernetes]
----

.. In the top toolbar from the notebook, click the menu:play[] icon, having the tooltip "Run this cell and advance".

.. Wait until the MLflow SDK and all its dependencies are loaded from the RHOAI index into the workbench.

.. After the `pip` command finishes, enter the following on the second cell of your notebook:
+
[source,python,subs="verbatim,quotes"]
----
import os
import mlflow

os.environ["MLFLOW_TRACKING_AUTH"]="kubernetes-namespaced"
mlflow.set_tracking_uri("https://mlflow.redhat-ods-applications.svc.cluster.local:8443")

print(mlflow.list_workspaces())
----
+
[NOTE]
====
In this example, we are using the _internal_ URL of the MLflow server, which works only for applications running in the same OpenShift cluster.
====

.. In the top toolbar from the notebook, click the menu:play[] icon.
The results should be an array containing a single `Workspace` object named `my-first-model`.
+
This notebook takes advantage of the integration between the RHOAI dashboard and its managed instance of the MLflow server.
It connects using the service account of the `test-evals` workbench, which is authorized to access the MLflow workspace corresponding to its `my-first-model` project.

.. You will not use the `test-mlflow.ipynb` notebook anymore, but do NOT delete the `test-evals` workbench because you will keep using it in the remaining activities of this course.

=== Summary

After completing these steps, you have verified that you have a minimal but functional MLflow instance, to which you can connect from applications running inside your RHOAI cluster and store data from your experiments.

== What's next

With MLflow deployed and verified, the next section introduces the architecture and setup of EvalHub.

////
Deploy MLFlow on Red Hat OpenShift AI for development
Edit the DSC resource to enable MLFlow
Configure MLFlow with a local SQL lite database and file-based storage using a PVC and the default storage class.
Verify the healthy of the MLFlow server deployment
Create an experiment using the RHOAI web UI to prove that the MLFlow server is functional
////