= Lab: Deploy EvalHub for Development

Objective::

Enable EvalHub on Red Hat OpenShift AI using the TrustyAI operator, configure its database, and install and configure the EvalHub CLI.

// Maybe split all CLI usage into its own lab?

WARNING: Work In Progress

== Before you begin

You need access to the predeployed Red Hat OpenShift AI (RHOAI) instance provided in your lab environment. Ensure you have:

* Access credentials for the RHOAI dashboard
* A web browser to access the RHOAI dashboard
* Access credentials for the OpenShift web console

Also ensure that you already deployed MLflow by following the instructions from the xref:ch2-deployment:s2-mlflow-deploy-lab.adoc[previous lab] because, if you enable EvalHub without having MLflow enabled, then EvalHub will not be able to save metrics on experiments from MLflow.

[NOTE]
====
If you already deployed MLflow, and you are in a hurry and need to quickly enable EvalHub in your demo instance, for example: you had to destroy and recreate it before completing all activities in this course, you can:

* Clone the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples.git[samples git repository^]
* Enter its `scripts` directory
* Log in to OpenShift in your demo instance as the `admin` user, using the `oc` command
* Invoke the `enable-evalhub.sh` script
====

== Instructions

You will enable TrustyAI on your Data Science Cluster singleton resource and deploy a development instance of the EvalHub server.
Then you will use a shell a Jupyter notebook to test connectivity and healthy of your EvalHub server.

As you perform this activity, you will alternate between two browser tabs:

* The Red Hat OpenShift web console
* The Red Hat OpenShift AI (RHOAI) dashboard

Once you open one of these tabs, keep it open because you may return to it later.

=== Install and configure the EvalHub Server

1. Verify that TrustyAI is already enabled in the data science cluster resource.

.. Open the OpenShift web console and log in as a user with `cluster-admin` rights.

.. In the left navigation pane, select menu:Ecosystem[Installed Operators].
Then click menu:Red Hat OpenShift AI[].

.. In the Red Hat OpenShift AI operator page, select the menu:Data Science Cluster[] tab.
Then click the menu:default-dsc[] resource.

.. In the `default-dsc` resource page, select the menu:YAML[] tab.
In the text editor, search for the `spec.components` field, and verify that `trustyai.managementState` is already set to `Managed`.
+
[source,yaml,subs="verbatim,quotes"]
----
...
spec:
  components:
    kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headless
...
    *trustyai:*
      *managementState: Managed*
      mcpGuardrailsMode: false
    aipipelines:
      managementState: Managed
...
----

.. Click menu:Cancel[] to leave the YAML editor without making changes.

2. Deploy a PosgreSQL database.

.. Open the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/blob/main/scripts/evalhubdb.yaml[course samples repository^] with a web browser and open the manifest `scripts/evalhubdb.yaml`.
Copy the entire contents of the manifest to the clipboard.

.. In the left pane, select menu:Home[Projects] and, in the search field, enter `redhat-ods`.
Then click the menu:redhat-ods-applications[] project.

.. In the toolbar, click the menu:+[] icon, with tooltip `Quick create` and select menu:Import YAML[].

.. In the Import YAML page, enter the manifests for a PVC, a deployment, and a service, which you already copied to your clipboard.

.. TBD Click menu:[Create].

.. TBD Verify that the database is ready and available

3. Configure your EvalHub instance by creating an EvalHub resource.

.. In the left navigation pane, select menu:Home[API Explorer].
Then enter `EvalHb` in the search field.
You will see only one resource types; click menu:EvalHub[].

.. In the EvalHub Resource details page, select the menu:Instances[] tab and verify that the selected project is still `redhat-ods-applications`.
Then click menu:Create EvalHub[].

.. In the YAML text editor, delete all of its sample contents and enter the following, which corresponds to the example from https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4/html/evaluating_ai_systems/evaluating-llms-with-evalhub_evaluate#evalhub-deploy-with-the-trustyai-operator_evaluate[2.3. Deploy EvalHub with the TrustyAI Operator^] in the Red Hat OpenShift AI product documentation with a couple chances:
+
--
... Addition of the `lighteval` provider
... The correct internal URL of the MLflow server
--
+
[source,yaml,subs="verbatim,quotes"]
----
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: EvalHub
metadata:
  name: evalhub
spec:
  replicas: 1
  database:
    type: postgresql
    secret: evalhub-db-credentials
  providers:
    - lm-evaluation-harness
    - garak
    - guidellm
    - lighteval
  collections:
    - safety-and-fairness-v1
  env:
    - name: MLFLOW_TRACKING_URI
      value: "https://mlflow.redhat-ods-applications.svc.cluster.local:8443"
----

.. Click menu:Create[] and, in the EvalHub details page, wait until the `Available` condition is `True` and the `Progressing` condition is `False`.

=== Test your EvalHub server using a shell

[start=3]
3. Verify that EvalHub is available from the RHOAI dashboard.

.. Open your RHOAI dashboard.
If it is already open, refresh your browser window.

.. In the left navigation pane, select menu:Develop & train[Evaluations].
The *Evaluations* page now displays the message `No existing evaluation runs`.
The page also displays a button named menu:Create Evaluation[].
Do not click it yet.

4. Verify that your EvalHub server is healthy.

.. Switch to your web browser tab which is open in the OpenShift web console.
If its web terminal connection has closed due to inactivity, click menu:Restart terminal[].

.. Run the following shell commands to get the EvalHub URL and access its health endpoint.
Your output should include the JSON field `status: healthy`.
+
[source,console,subs="verbatim,quotes"]
----
$ oc project redhat-ods-applications
Now using project "redhat-ods-applications" on server "https://172.30.0.1:443".
$ EVALHUB_URL=https://$(oc get routes evalhub -o jsonpath='{.spec.host}')
$ curl -sk $EVALHUB_URL/api/v1/health
{"status":"healthy","timestamp":"2026-07-27T23:24:06.894598885Z","build":"0.3.0"}
----

5. Install the EvalHub CLI in your web terminal.
+
In a regular shell, we would recommend installing the EvalHub CLI in a Python virtual enviroment.
But, with a single-purpose web terminal, it is OK to install the EvalHub CLI on the system Python of the web terminal image.

.. Run the folling shell commands to install the EvalHub CLI using `pip` and configure it to connect to the EvalHub server on its OpenShift cluster.
+
Notice these commands refer to the `EVALHUB_URL` shell variable you set during the previoius step.
+
[source,console,subs="verbatim,quotes"]
----
$ pip install "eval-hub-sdk[cli]"
GRAB OUTPUT
$ evalhub config set base_url $EVALHUB_URL
GRAB OUTPUT
$ evalhub config set tenant my-first-model
GRAB OUTPUT
$ TOKEN=$(oc whoami -t)
$ evalhub config set token $TOKEN
GRAB OUTPUT
----

.. Verify that the EvalHub CLI can connect to the EvalHub server and list its known evaluation providers.
+
[source,console,subs="verbatim,quotes"]
----
$ evalhub health
GRAB OUTPUT
$ evalhub providers list
GRAB OUTPUT
----

=== Summary

After completing these steps, you have verified that you have a minimal but functional EvalHub instance, which you can use to run evaluation jobs.

== What's next

With both MLFlow and EvalHub deployed, the next chapter introduces model evaluation using EvalHub providers and benchmarks.

////
Deploy EvalHub on Red Hat OpenShift AI for development
Edit the DSC resource to enable TrustyAI
Deploy an in-cluster PostgreSQL database
Configure EvalHub using that database in the redhat-ods-applications namespace.
Verify the healthy of the EvalHub server deployment
Install the EvalHub CLI from packages.redhat.com instead of from upstream
Configure the EvalHub CLI and connect to the remote RHOAI instance
////