= Lab: Deploy EvalHub for Development

Objective::

Enable EvalHub on Red Hat OpenShift AI using the TrustyAI operator, configure its database, and install and configure the EvalHub CLI.

// Maybe split all CLI usage into its own lab?

WARNING: Work In Progress

== Before you begin

You need access to the predeployed Red Hat OpenShift AI (RHOAI) instance provided in your lab environment. Ensure you have:

* Access credentials for the RHOAI dashboard
* A web browser to access the RHOAI dashboard
* Access credentials for the OpenShift web console

Also ensure that you already deployed MLflow by following the instructions from the xref:ch2-deployment:s2-mlflow-deploy-lab.adoc[previous lab] because, if you enable EvalHub without having MLflow enabled, then EvalHub will not be able to save metrics on experiments from MLflow.

[NOTE]
====
If you already deployed MLflow, and you are in a hurry and need to quickly enable EvalHub in your demo instance, for example: you had to destroy and recreate it before completing all activities in this course, you can:

* Clone the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples.git[samples git repository^]
* Enter its `scripts` directory
* Log in to OpenShift in your demo instance as the `admin` user, using the `oc` command
* Invoke the `enable-evalhub.sh` script
====

== Instructions

You will enable TrustyAI on your Data Science Cluster singleton resource and deploy a development instance of the EvalHub server.
Then you will use a shell to test connectivity and healthy of your EvalHub server.

As you perform this activity, you will alternate between three browser tabs:

* The Red Hat OpenShift web console
* The Red Hat OpenShift AI (RHOAI) dashboard
* A Jupyter notebook from the `test-evals` workbench


Once you open one of these tabs, keep it open because you may return to it later.

=== Install and configure the EvalHub Server

1. Verify that TrustyAI is already enabled in the data science cluster resource.

.. Open the OpenShift web console and log in as a user with `cluster-admin` rights.

.. In the left navigation pane, select menu:Ecosystem[Installed Operators].
Then click menu:Red Hat OpenShift AI[].

.. In the Red Hat OpenShift AI operator page, select the menu:Data Science Cluster[] tab.
Then click the menu:default-dsc[] resource.

.. In the `default-dsc` resource page, select the menu:YAML[] tab.
In the text editor, search for the `spec.components` field, and verify that `trustyai.managementState` is already set to `Managed`.
+
[source,yaml,subs="verbatim,quotes"]
----
...
spec:
  components:
    kserve:
      managementState: Managed
      rawDeploymentServiceConfig: Headless
...
    *trustyai:*
      *managementState: Managed*
      mcpGuardrailsMode: false
    aipipelines:
      managementState: Managed
...
----

.. Click menu:Cancel[] to leave the YAML editor without making changes.

2. Deploy a PosgreSQL database.

.. Open the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/blob/main/scripts/evalhubdb.yaml[sample evalhub db deployment^] from the course samples repository with a web browser and open the manifest `scripts/evalhubdb.yaml`.
Copy the entire contents of the manifest to the clipboard.
+
[NOTE]
====
This is a minimal PostgreSQL deployment.
It is not listed here because if its size, and you would not use such a simplisitic database deployment for a real development or production instance of EvalHub. 

You are free to use your preferred OpenShift template, helm chart, or database operator instead.
Ideally, use something that is supported by your organization IT department, and for which you can expect product support from a vendor.
====

.. In the left pane, select menu:Home[Projects] and, in the search field, enter `redhat-ods`.
Then click the menu:redhat-ods-applications[] project.

.. In the toolbar, click the menu:&#43;[] icon, with tooltip `Quick create` and select menu:Import YAML[].

.. In the Import YAML page, enter the manifests for a PVC, a deployment, and a service, which you already copied to your clipboard, and click menu:[Create].

.. You should see a page with the message `Resources successfully created`. 
Click on the menu:evalhubdb[] deployment, the one with a "D" icon.

.. In its deployment details page, wait until you see a blue cicle with a label of "1 Pod", indicating one pod from that deployment is running.
Then scrool down to the *Conditions* table, and verify there is a row of type `Available` with status `True`.

3. Configure your EvalHub instance by creating a secret and an EvalHub resource.

.. Open the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/blob/main/scripts/evalhub-db-credentials.yaml[sample evalhub db secret^] from the course samples repository with a web browser and open the manifest `scripts/evalhub-db-credentials.yaml`.
Copy the entire contents of the manifest to the clipboard.
+
The full secret manifest is listed here, just for your reference:
+
[source,YAML,subs="verbatim,quotes"]
----
include::1@samples:scripts:example$evalhub-db-credentials.yaml[]
----

.. In the left navigation pane, select menu:Workloads[Secrets]  and verify that the selected project is still `redhat-ods-applications`.
Then click menu:Create[From YAML].

.. In the *Create Secret* page, enter the manifests for a secret which you already copied to your clipboard, and click menu:Create[].

.. In the *Secret details* page, you can scroll down and click menu:Reveal values[] to see the database connection URL.
It contains the database user name, password, and other connection parameters which match the database deployment you created in the previous step.

.. In the left navigation pane, select menu:Home[API Explorer].
Then enter `EvalHb` in the search field.
You will see only one resource, so click menu:EvalHub[].

.. Open the https://github.com/RedHatQuickCourses/rhoai-mlflow-samples/blob/main/scripts/evalhub.yaml[sample evalhub manifest^] from the course samples repository with a web browser and open the manifest `scripts/evalhub.yaml`.
Copy the entire contents of the manifest to the clipboard.
+
[NOTE]
====
That manifest  corresponds to the example from https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4/html/evaluating_ai_systems/evaluating-llms-with-evalhub_evaluate#evalhub-deploy-with-the-trustyai-operator_evaluate[2.3. Deploy EvalHub with the TrustyAI Operator^] in the Red Hat OpenShift AI product documentation with a couple changes:

* Addition of `lighteval` to the list of providers
* The correct internal URL of the MLflow server
====
+
The full manifest is listed here, just for your reference:
+
[source,YAML,subs="verbatim,quotes"]
----
include::1@samples:scripts:example$evalhub.yaml[]
----

.. In the EvalHub resource details page, select the menu:Instances[] tab and verify that the selected project is still `redhat-ods-applications`.
Then click menu:Create EvalHub[].

.. In the YAML text editor, delete all of its sample contents and paste the evalhub manifest which you already copied to the clipboard.

.. Click menu:Create[] and, in the EvalHub details page, wait until the `Ready` condition is `True`.

=== Test your EvalHub server using a shell

[start=3]
3. Verify that EvalHub is available from the RHOAI dashboard.

.. Open your RHOAI dashboard.
If it is already open, refresh your browser window so it picks changes to the dashoard pages and navigation.

.. In the left navigation pane, select menu:Develop & train[Evaluations].
The *Evaluations* page now displays the message `No existing evaluation runs`.
The page also displays a button named menu:Create Evaluation[].
Do not click it yet.

4. Verify that your EvalHub server is healthy.

.. If you have a web browser tab already open on your workbench, from performing the previous lab, swith to it.
+
If not, click menu:Projects[], in the left navigation pane, and select menu:All projects[] in the menu:Project[] field.
Then enter `my` in the *Filter by name* field and click menu:my-first-model[] in the list of projects.
Finally, in the Projects page for `my-first-model`, select the menu:Workbenches[] tab and click menu:test-evals[] to open the workbench in a new browser window.

.. Click the menu:Terminal[] icon, with tooltip `Start a new terminal session`.

.. Run the following shell commands to get the EvalHub URL and access its health endpoint.
Your output should include the JSON field `status: healthy`.
+
WARNING: The workbench runs with a service account instead of with the admin user, so it has no access to other projects and kuberentes resouces. :-(
+
[source,console,subs="verbatim,quotes"]
----
$ oc project redhat-ods-applications
error: You are not a member of project "redhat-ods-applications".
You are not a member of any projects. You can request a project to be created with the 'new-project' command.
### Expected:
Now using project "redhat-ods-applications" on server "https://172.30.0.1:443".
$ EVALHUB_URL=https://$(oc get routes evalhub -o jsonpath='{.spec.host}')
$ curl -sk $EVALHUB_URL/api/v1/health
{"status":"healthy","timestamp":"2026-07-27T23:24:06.894598885Z","build":"0.3.0"}
----

5. Install the EvalHub CLI in your workbench.
+
In a regular shell, we would recommend installing the EvalHub CLI in a Python virtual enviroment.
But, with a jupyter notebook, it is OK to install the EvalHub CLI on the system Python of its workbench image.

.. Run the folling shell commands to install the EvalHub CLI using `pip` and configure it to connect to the EvalHub server on its OpenShift cluster.
+
Notice these commands refer to the `EVALHUB_URL` shell variable you set during the previoius step.
+
WARNING: The web terminal does NOT contain a Python runtime. Must switch to a workbenck. :-(
+
[source,console,subs="verbatim,quotes"]
----
$ pip install "eval-hub-sdk[cli]"
bash: pip: command not found
$ evalhub config set base_url $EVALHUB_URL
GRAB OUTPUT
$ evalhub config set tenant my-first-model
GRAB OUTPUT
$ TOKEN=$(oc whoami -t)
$ evalhub config set token $TOKEN
GRAB OUTPUT
----

.. Verify that the EvalHub CLI can connect to the EvalHub server and list its known evaluation providers.
+
[source,console,subs="verbatim,quotes"]
----
$ evalhub health
GRAB OUTPUT
$ evalhub providers list
GRAB OUTPUT
----

=== Summary

After completing these steps, you have verified that you have a minimal but functional EvalHub instance, which you can use to run evaluation jobs.

== What's next

With both MLFlow and EvalHub deployed, the next chapter introduces model evaluation using EvalHub providers and benchmarks.

////
Deploy EvalHub on Red Hat OpenShift AI for development
Edit the DSC resource to enable TrustyAI
Deploy an in-cluster PostgreSQL database
Configure EvalHub using that database in the redhat-ods-applications namespace.
Verify the healthy of the EvalHub server deployment
Install the EvalHub CLI from packages.redhat.com instead of from upstream
Configure the EvalHub CLI and connect to the remote RHOAI instance
////