= Lab: Deploy EvalHub for Development

Objective::

Enable EvalHub on Red Hat OpenShift AI using the TrustyAI operator, configure its database, and install and configure the EvalHub CLI.

WARNING: Not started  yet.

== Before you begin

Describe requirements, such as customer portal accounts, Red Hat Developer free sub, already configured machines, access to container registries, etc.

== Instructions

High-level summary of what you will perform in this lab, but more detailed than the objective.

1. Task or outcome.

.. Something to do, using a graphical or web UI.
Click menu:Save As[] to save your work.

.. More things to do

2. Task or outcome.

.. Something to do, using a shell.
+
[source,console,subs="verbatim,quotes"]
--
$ *command --options fixed-arguments _variable-arguments_*
output of the command
highlight *something* in the output
--


.. More things to do.
Press kbd:[Ctrl+C] to interrupt.

Summary of what you acomplished.

== What's next

With both MLFlow and EvalHub deployed, the next chapter introduces model evaluation using EvalHub providers and benchmarks.

////
Deploy EvalHub on Red Hat OpenShift AI for development
Edit the DSC resource to enable TrustyAI
Deploy an in-cluster PostgreSQL database
Configure EvalHub using that database in the redhat-ods-applications namespace.
Verify the healthy of the EvalHub server deployment
Install the EvalHub CLI from packages.redhat.com instead of from upstream
Configure the EvalHub CLI and connect to the remote RHOAI instance
////