= Evaluation Concepts for AI Applications

Objective::

Describe how evaluating AI-enabled applications differs from testing traditional applications and identify the roles of MLFlow and EvalHub in Red Hat OpenShift AI.

WARNING: Work In Progress

== Evaluating non-deterministic applications

Traditional software engineering focuses on testing approaches for deterministic applications, such as unit tests and functional testings, and integrating that testing with other kinds of tests, such as performance tests and security scans.

AI-enabled applications, such as chat bots and agents, benefit from those traditional testing approach but they require the addition of tests designed for their non-deterministic nature.
Those tests are called _evaluations_.

It is a known fact that large-language models (LLMs) are based on probabilistic pattern-matching.
They may produce different outputs from the same input data.
Sometimes those differences are inconsequential, such as a different wording of the same statements, but sometimes those differences make their answers factually incorrect or open to misleading interpretation.

Aproaches such as guard rails can mitigate the probabilistic nature of LLMs, but cannot sove it entirely.
Other approaches, such as setting the _temperature_ parameter to zero, to force a model to always provide the same response, also degrates a model performance when planning, exploring, and researching.
The randomness of LLMs actually enable them to work in imprecise scenarios and  emulate creativity, probem-solving, or finding new insights.
Without randomness, LLMs can only output facts which are alredy explicity stated in their training data.

Model evaluations become popular quite early as a way of demonstrating the capabilities of LLMs and comparing them with each other based on criteria such as ability to provide correct answers to general knowledge questions, science questions, and other domain areas.

Other popular use cases for model evaluations include assessing how easy is to trick a model into providing a harmful response, or how capable they are at following instructions.

=== Evaluating models and applications

AI-enabled applications usually perform more than just sending a prompt to a model and displaying its output.
Even chat bots are nowadays expected to function as _agentic applications_ and rely on sophisticated _harnesses_ which might include data such as:

* A _System prompt_ with general instructions regarding the application's intended usage.

* Varios _skills_ which guide the model on performing specific tasks, and which are seleled by the model based on the received prompt.

* Collections of _tools_, some provided by the agentic application itself, and some provided by external MCP servers.

* Data from _retrieval augumented generation (RAG)_ sources, for example documentation of processes and legal or financial rules.

* Various levels of _memory_ which add to the request information about the current user, past interactions, or the what's in the end user applications's screen.

Evaluating models, by themselves, is useful and necessary because the capabilities and performance of an LLM vary with their target hardware and configuration settings.
You should assess that, on your specific environment, a model performs as expected regarding correctness of its outputs, resistance to bad prompts, frequency of hallucinations, and tool capability.

But evaluating a model is not sufficient to assess the performance of agentic applications.
You must evaluate individual components of its harness, such as their RAG sources and MCP servers.
You must also evaluate the harness as a whole and experiment with different combinations, for example:

* Among different MCP servers that integrate with the same back-end systems, the most powerful MCP server may perform worse when combined with other elements of a harness.

* A simpler MCP server, which performs worst individually, may be better when combined with a specific system prompt or set of skills.

* Preloading data from memory and RAG may be better or worse than letting the model request such data on-demand from MCP servers.

Most applications require multiple evaluations, of different kinds, to assess a good enough performance and quality of their responses.
They also require repeated evaluations to catch regressions when any piece of their harnesses change, and their evaluations sets will grow over time, as you discover different usage scenarios and failure modes.

=== Evaluations during development and production

Evaluations are conceptually closer to performance tests than to unit tests.
You cannot just test one example of "good" input plus one example of each known corner case.
You must test multiple "good" inputs and also multiple examples of each corner case, because of the non-deterministic nature of LLMs.
You may require large evaluation data sets and also curate custom data sets which are specific for your usage scenarios and business processes.

Besides, your evaluations are constrained by the availability of specialized hardware such as GPUs and specialized memory for storing models and tokens.
You will not run them for every commit.

Early during development, you evaluations will be exploratory and interactive, intended to select an optimal harness, and use a small data set.
Once your harness and model selections are more solid, you will increase the size of your evaluation data sets and add a larger variety of evaluations to assess performance, correctness, and the need for specialized guardrails.
You will also start to run evaluations automatically, as part of your CI/CD processes.

Once you release your agent to production, or to its first external test users, you will collect samples (traces) of actual inputs and outputs to assess actual performance of your harness, and feedback some of that data to improve the evaluations for the next development interaction of your agent.

It is recommended that you work proactively: instead of relying just on user feedback about the quality of your application, such as thumbs up and down, and customer support tickets complaining about errors, you should take samples of actual usage data as additional evaluation data sets and compare the results with evaluations from your synthetic and development evaluation data sets.

You may learn that actual behavior differs significantly from intended and tested behavior, and consequently improve both your harness and its evaluations.

== Running evaluations with MLflow

MLflow provides fundamental observability and experiment-tracking capabilities that enable developers and data scientists to ensure their applications work beyond a demonstration and perform as expected in production.

MLflow is a popular library for agentic evaluations.
It requires encapsulating your agent and its harness as a _predictor function_, and them creating custom code to invoke your prediction function together with  _scorers_ and _judges_, some of which are themselves based on LLMs.

It is up to the developer packaging their custom evaluation code, based on the MLflow SDK, as a KubeFlow pipeline or as a Tekton task (for OpenShift Pipelines), among other ways of operationalizing reproducible execution of MLflow evaluations.

MLflow is also a popular library for tracing agentic applications, including their usage of RAG sources, tools, and multi-turn conversations with LLMs.

Typical usage of MLflow libraries store evaluation results as part of a trace, and multiple traces are part of an _experiment_.
An MLflow experiment could include other kinds of data and other kinds of experiment runs besides traces.

Using the MLflow SDK, you can also retrieve data from traces as evaluation data sets for running evaluations, closing the loop from development to production, or from early development tests to test users.

== Running evaluations with EvalHub

Most kinds of AI evaluations are run by custom code, using varied libraries which specialize in different kinds of evaluations, such as safety and domain expertise.
As you can guess, maintaining and operationalizing such custom code quickly becomes a challenge.

EvalHub is an open-source evaluation orchestration platform designed to run systematic, multi-framework tests for large language models (LLMs), agents, and AI systems.

EvalHub standardizes how you operationalize and store results of your evaluations.
It provides a number of _evaluation providers_, each specific for an _evaluation framework_ and their specific _benchmarks_.
EvalHub also offers a standard syntax to combine multiple providers and select a subset of their benchmarks in a _collection_, which makes it easier to reproduce evaluation runs.

EvalHub also improves governance of your evaluations by storing their results on on OCI container images, for immutable auditability storage.

As included with RHOAI 3.4, EvalHub supports a number of providers focused on evaluating models, such as Garak and LightEval.
The EvalHub community is very active and it is expanding its set of community-supported providers, which add capabilities for running other kinds of evaluations, including agent evaluations.
As these community providers mature, some of them will be included and supported with future releases of RHOAI.

== Comparing and integrating EvalHub with MLflow

It is not a choice of using either EvalHub or MLflow for your evaluations.
Most of the times, it is about how you will use each of them, and sometimes them together, during your AI applicaiton lifecycle.

While MLflow provides building blocks for creating custom evaluations for your agents and its business needs, EvalHub provides standard benchmark collections which are ready to run and compare how different models perform on your specific deployment environment. 
EvalHub also enables customizing those collections, by selecting different benchmarks or the weights and thresholds from each individual benchmark to compose the overall evaluation score.

RHOAI uses MLflow as its main observability feature.
Multiple components of RHOAI integrate with MLflow to store traces and metrics as MLflow experiments.
Among those components, EvalHub can store evaluation results from any provider and benchmark as MLflow experiments.
This way, results from all your evaluations, be them managed by EvalHub or not, are stored and visualized together in MLflow.

Unfortunately, at the time of RHOAI 3.4, EvalHub is not yet cappable of running MLflow evaluations directly.
It would require building custom code using the bring your own framework (BYOF) API from EvalHub to run an MLflow evaluation.

This course does not present BYOF, but provides you with sufficient information so you could use EvalHub for run model evaluations and MLflow for agent evaluations, and combine both as dicrete steps in a KubeFlow pipeline, while aggregating results of all these evaluations in MLflow.

== What's Next

Now that you understand the key evaluation concepts for AI applications, the next activity explores the hands-on lab environment and the next chapter deploys MLflow and EvalHub on Red Hat OpenShift AI.

//Now that you understand the key evaluation concepts for AI applications, test your knowledge with a quiz on MLFlow and EvalHub fundamentals.

////
The need for evaluations
How testing AI-enabled applications (evaluation) differs from testing traditional applications (unit/integration/functional/scalability testing)
Evaluating models as a step in a larger process which also includes evaluating agents
Silent failures and AIOps concepts
Evaluation-Driven Development (EDD)
Introduction to MLFlow in Red Hat OpenShift AI
Summary of MLFlow features supported or recommended in an RHOAI instance. Focus on MLFlow features for generative AI applications, especially observability and reproducibility.
Quick introduction to the concept of experiments in MLFlow and how it applies to agentic application development.
Refer to the previous curious for a deeper introduction to MLflow and its SDK
Introduction to EvalHub in Red Hat OpenShift AI
EvalHub is a hub for all kinds of evaluation tasks, but currently (RHOAI 3.4) only supports model evaluation.
Summary of the EvalHub features
Different kinds of evaluations, ex: safety, security, and performance.
Quick introduction to the concepts of providers, benchmarks, collections, metrics, and BYOF on EvalHub
Observability: EvalHub can/should stores data from evaluation jobs as Experiment runs in MLflow
Governance: EvalHub can/should store cryptographically signed evaluation results on an OCI registry
There's a note in RHOAI 3.5EA known issues about the need of installing/enabling MLflow before EvalHub. In fact, I experienced, with RHOAI 3.4, some of the known issues listed only for 3.5EA
////