= Lab: Explore the Learning Environment

Objective::

Navigate the provided demo environment, identify enabled Red Hat OpenShift AI features, and verify that the predeployed model is functional.

WARNING: Not started  yet.

== Before you begin

Describe requirements, such as customer portal accounts, Red Hat Developer free sub, already configured machines, access to container registries, etc.

== Instructions

High-level summary of what you will perform in this lab, but more detailed than the objective.

1. Task or outcome.

.. Something to do, using a graphical or web UI.
Click menu:Save As[] to save your work.

.. More things to do

2. Task or outcome.

.. Something to do, using a shell.
+
[source,console,subs="verbatim,quotes"]
--
$ *command --options fixed-arguments _variable-arguments_*
output of the command
highlight *something* in the output
--


.. More things to do.
Press kbd:[Ctrl+C] to interrupt.

Summary of what you acomplished.

== What's next

Now that you are familiar with the learning environment, the next chapter covers how to deploy MLFlow and EvalHub for development on Red Hat OpenShift AI.

////
Explore the learning environment
Quick exploration of the provided demo environment: enabled RHOAI features and predeployed projects and models
Quick exploration of the provided demo environment: Evaluations are unavailable
Sanity check using either a playground or a workbench
////